### ISSUE TITLE
Quark sitting on stairs.

### ISSUE THREAD

**Issue by Yekul10** [Kaydax/Ido#10]
Quark has an ability for you to sit on stairs, but with this mod enabled, it makes you crawl under the block.
Mods that could cause the problems: Quark, Ido, First Person Render 2, More Player Models, Mobends, Custom NPCs, Vanilla Fix, and Dynamic Stealth. I'm pretty sure the other 180 mods aren't causing this problem.
![2019-07-27_12 37 58](https://user-images.githubusercontent.com/29359831/61999780-7241ab00-b096-11e9-84d7-80886406085b.png)

**Comment by Kaydax** [comment]
Should be fixed in the next patch, if not more testing will be done to see if there is a way to fix it.
