### ISSUE TITLE
Collision with Chisels & Bits

### ISSUE THREAD

**Issue by M0DSteam** [Kaydax/Ido#12]
When you do any kind of building using [Chisels & Bits](https://www.curseforge.com/minecraft/mc-mods/chisels-bits) and enter the part of the block which is empty (no bits on it) you just crawl into the block, which is extremely annoying, as you may create stairs using the mod and then you just crawl, get up, crawl, get up, and so on...

To Recreate This: you have to install both C&B and Idō, create any kind of block using Chisels & Bits for example, a stair, and try to walk into is, as anyone would use a stair.

I hope it is possible to fix, if not, then maybe there should be a config to deactivate parts of the mod, as this makes C&B to become annoying to use, thanks for your time :)

**Comment by Kaydax** [comment]
May be an issue with collision checking. Will look more into it to see what can be done

**Comment by PulzHF** [comment]
Hello, has there been any progress on this issue?

**Comment by Kaydax** [comment]
> Hello, has there been any progress on this issue?

soon™

I have been busy with other things and will fix some things in due time

**Comment by Kaydax** [comment]
> Hello, has there been any progress on this issue?

I will try to push a fix in a bit as I'm testing to see the issue

**Comment by PulzHF** [comment]
> I will try to push a fix in a bit as I'm testing to see the issue
Glad to hear that :)

**Comment by Kaydax** [comment]
I have fixed the issue and will be pushing it into the next release once I finish up with fixing the other issues
