### ISSUE TITLE
broken crawling with boats and minecarts

### ISSUE THREAD

**Issue by WarlordWossman** [Kaydax/Ido#13]
You crawl under the boat if there is a block under you and minecarts also have the player stuck in the ground. This is rather critical since it's pretty game breaking and can kill you in survival as well.

In general I would like to suggest crawling to be optional in the config, I expect many people mainly want swimming and sneaking.

**Comment by Syndaryl** [comment]
I like the crawling, but the minecart issue is pretty bad.

**Comment by Kaydax** [comment]
Fix will be pushed in 1.0.4. Config will be coming in 1.1.0 with the ability to change different settings and disable / enable features
