### ISSUE TITLE
Cannot exit a minecart

### ISSUE THREAD

**Issue by Syndaryl** [Kaydax/Ido#14]
A side effect (I think) of the problem from #13 is that when you're in a minecart, you can't exit by pressing shift, only by breaking the cart or using an activator rail.

**Comment by Syndaryl** [comment]
Unfortunately you can't use buttons or levers when you're stuck like this, so you have to rig up a detector rail with your activator rail, which is even more jury rigging.

**Comment by Kaydax** [comment]
Fixed in 1.0.4 and the Update will be released soon

**Comment by Syndaryl** [comment]
Thanks for the prompt action :)
