### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by aimbait** [Kaydax/Ido#15]
First of all, great mod. This combined with RandomPatches makes the movement feel almost identical to 1.14, but there is some issues.
1. (minor) The Elytra was slightly modified as a result of this mod, it looks as though there may be a different animation on it, the same as swimming, I believe. Also, things like if you have a Cape or a dyed Elytra from Quark revert to the normal Elytra with this mod.
2. (major) Any vehicles like Minecart, Boat, or Quark sitting in stairs are completely broken, can cause deaths in Survival.

**Comment by Kaydax** [comment]
Elytra flying animation is being fixed by bagu now. The issues with riding entities should be already fixed in the latest commit. After the elytra is fixed the update will be released
