### ISSUE TITLE
Can't Swim in 1-Block Deep Water

### ISSUE THREAD

**Issue by WenXin20** [Kaydax/Ido#18]
Minecart 1.12.2
Forge v14.23.5.2838
Idō v1.0.4

I tried swimming in an area with only one-block deep water, but swimming doesn't work until I enter a spot with water at least 2 blocks deep.

**Comment by Kaydax** [comment]
Is your head under the water?

**Comment by WenXin20** [comment]
No, it's not. Is that required to swim?

**Comment by Kaydax** [comment]
Yes. You must be under the water to start swimming. This is exactly the same as how 1.13 and 1.14 swimming works. Since this is not an issue I'm going to close the ticket

**Comment by WenXin20** [comment]
Alright, thanks
