### ISSUE TITLE
[Bug + Suggestion] Invisible Player + Less vertical movement

### ISSUE THREAD

**Issue by Fogrits** [Kaydax/Ido#20]
Ido version: 1.0.4 (1.12.2)
Forge 2838

[Video proof](https://youtu.be/KwBeCrT5FSM)

Also, could you nerf player's vertical movement underwater? It feels like I can go from the water surface to the bottom of the ocean in 2 seconds

**Comment by Kaydax** [comment]
Video is unavailable for me

**Comment by Fogrits** [comment]
oops, my bad, had it private
try it now

**Comment by Fogrits** [comment]
I'm doing a list of my installed mods to see if you can find any incompatible mods

**Comment by Kaydax** [comment]
Never seen an issue like this before, very odd. Yah get me that list of mods so I can check

**Comment by Fogrits** [comment]
All | mods | installed
------------------------|---------------------------|-----------------
Arcane Essentials 		| Just Enough Integration	| Phosphor
AutoRegLib 		  		| JourneyMap				| Placebo
Baubles 				| Just Enough Resources		| ProjectRed
Bauble Enhancements 	| Mo' Villages 				| Quark + Quark Oddities
Bauble of Undying 		| MrTJPCore 				| Random Patches
Bauble Shulker Boxes	| Natural Nether Portals	| RebornCore
Beneficium 				| Nether Portal Fix 		| Reborn Storage
Better Portals 			| Phosphor 					| Refined Storage
Biome Specific Dungeons | FastFurnace 				| Redstone Arsenal
Bookshelf 				| Fast Leaf Decay 			| Redstone Flux
Bring me the Rings 		| FastWorkbench				| Redstone Repository
Building Gadgets 		| FoamFix 					| Refined Storage + RS Addons + Infinite Wireless
CarryOn 				| Forgelin					| Rex's Additional Structures
Ceiling Torch 			| Forge Multipart CBE		| Seeds for Wizardry
Clumps 					| FTBLib 					| Shipwrecks
CodeChickenLib 			| FTB Utilities 			| Steve's Carts Reborn
CoFH Core 				| GottschCore				| Surge
CoFH World 				| Ido 						| Swing Through Grass
Cosmetic Armor Reworked | Inventory Tweaks 			| The One Probe
Dark Utilities 			| Just Enough Items			| Thermal Suite (Expansion, Foundation, Dynamics and Innovation)
Diet Hoppers 			| Just Enough Integration	| Toast Control
Doomlike Dungeons 		| JourneyMap				| Traverse
dotHack Weapons			| Just Enough Resources		| Treasure2
Dungeons 2 				| Mo' Villages				| VanillaFix
Electrobob's Wizardry 	| MouseTweaks				| YABBA
Elevators 				| MrTJPCore					
Enchantment Descriptions| Natural Nether Portals				
Enchantments Exchanger	| Nether Portal Fix

**Comment by Kaydax** [comment]
Try removing carryon and see if that fixes anything

**Comment by Fogrits** [comment]
Removing CarryOn did not fix the issue

**Comment by Kaydax** [comment]
What mods do you have that change the player in any way

**Comment by Fogrits** [comment]
Directly, I think Cosmetic Armor (replaces the worn armor with something else at your choice)

**Comment by Fogrits** [comment]
Even after removing Cosmetic Armor I couldn't fix it

**Comment by Kaydax** [comment]
I'm talking about things that replace the playermodel

**Comment by Fogrits** [comment]
I don't have any mods that do this, only mods that add extra rendering (eg: Baubles and such)

**Comment by Fogrits** [comment]
gonna remove all the mods and try slowly readding them back until the issue comes back

**Comment by Fogrits** [comment]
Found the culprit, it was Better Portals (dunno why and dunno what it does with the player rendering)

**Comment by Fogrits** [comment]
So that the culprit was found, Is there a way to fix it?

**Comment by Kaydax** [comment]
I never found an issue with swimming or crawling with betterportals, but it may be do to the fact that betterportals renders the multiplayer version of the player on singleplayer. Are you using betterportals 2 or 1?

**Comment by Fogrits** [comment]
0.2.4 (the latest one)

**Comment by Kaydax** [comment]
Ah i see the exact issue here. Because of the way BetterPortals handles rendering with the player, I cannot just simply do a fix on this. This is up to him to try and fix it from what it seems, and also the fact that BetterPortals is way out of my league as its made using kotlin, of which I know none of. I will make an issue there explaining the issue.

**Comment by Kaydax** [comment]
https://github.com/Johni0702/BetterPortals/issues/200

I have made the issue here

**Comment by Kaydax** [comment]
Also I will try to see what I can do on the front of changing the way the player moves in water vertically

**Comment by Fogrits** [comment]
Ok, thanks :)
Currently the vertical movement feels way off in comparison with 1.13/14, the player rises and dives way too fast
