### ISSUE TITLE
When walk on certain blocks from Primal Core, player is forced to sneak

### ISSUE THREAD

**Issue by Fireztonez** [Kaydax/Ido#21]
Hello,
I found a strange issue, when I walk on somes blocks from [Primal Core](https://www.curseforge.com/minecraft/mc-mods/primalcore) (Mostly when the hitbox is smaller than a normal block, like Netjry Salt Flat) the player is forced to sneak on it, when IDO is installed... This is pretty annoying, specially when you have a bow in your hand. Especially when you have a bow in your hotbar, with Quark to install (And Rotate arrow types enabled)... You are stock with the bow in your hand and can't do anything. unless changing

I know PrimalCore mod is not Open Source, but I'm pretty sure An Sar (Unless, I will talk to him directly!!) can send you part of the codes sources if you need, question of finding where the issue came from...

**Version:**
Minecraft Forge: 1.12.2 - 14.23.5.2838
IDO: 1.0.4
PrimalCore: 1.8

**Comment by Kaydax** [comment]
This sounds like a collision detection issue. I am working on fixed for many things and the next update should fix this. But I will look more into this

**Comment by Fireztonez** [comment]
ok, nice!

**Comment by Kaydax** [comment]
Working on a fix for this now
