### ISSUE TITLE
nether portal issues

### ISSUE THREAD

**Issue by WarlordWossman** [Kaydax/Ido#23]
Until today going through nether portals rarely made me crawl which wasn't too bad but today I suffocated in a wall going through a nether portal, pretty sure this has to do with Ido since it didn't ever happen to me in thausands of hours of playing vanilla survival.

**Comment by Kaydax** [comment]
What other mods are you currently using?

**Comment by WarlordWossman** [comment]
https://github.com/WarlordWossman/Gluon/blob/master/modlist.txt

**Comment by Kaydax** [comment]
I am working on a collision check fix update so this may get patched during that

**Comment by Kaydax** [comment]
Seems the issue has been fixed on my end. I will be pushing the update once its finished
