### ISSUE TITLE
Elytra when flying into water will not start swimming

### ISSUE THREAD

**Issue by futurenp** [Kaydax/Ido#24]
When you fly into water and don't touch the bottom, you will still be in elytra mode, and pressing sprint will not allow you to go into swimming mode and causes issues with being on the surface of the water.

**Comment by WarlordWossman** [comment]
Some weird elytra spamming and trying to swim made me go 15 m/s without any speed effects or depth strider, def some weirdness going on between elytra and the swimming mechanic

**Comment by Kaydax** [comment]
Def broken. Fix may be easy. Trying to take my time on updates to keep everything clean and working instead of pumping them out. Sorry if I take awhile to fix things

**Comment by WarlordWossman** [comment]
No worries, I prefer the clean way over hastely hacking something.
On the topic: After a bit of testing it seems like if you go into swim mode and them deploy your elytra underwater you can reach those high speeds.

**Comment by Kaydax** [comment]
I seem to not have an issue with it in 1.0.6 as I fixed up a few things. Update and you should be good now
