### ISSUE TITLE
Swimming doesn't work with double-tapping W

### ISSUE THREAD

**Issue by comp500** [Kaydax/Ido#25]
Minecart 1.12.2
Forge v14.23.5.2838
Idō v1.0.4

In Minecraft, there are two ways to sprint and swim - you can press ctrl or you can double-tap W to start sprinting. Idō doesn't seem to support double-tapping W for swimming, it only supports pressing ctrl.

This was tested in singleplayer, I don't know if the issue occurs in multiplayer as well.

**Comment by Kaydax** [comment]
I never tried that in 1.13 / 1.14, is it like that at all? If so then I can try and add it

**Comment by comp500** [comment]
Yep, I always use double-tapping W to swim in 1.13/1.14.

**Comment by Kaydax** [comment]
Works fine for me but I'm in my dev environment atm so IDK if any of my changes effected anything or not. I will be pushing the update out soon

**Comment by Kaydax** [comment]
So after looking into it, 1.12.2 is to blame. Even without the mod you can still only use ctrl to sprint when under water.
