### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by N4TH4NOT** [Kaydax/Ido#28]
When swiming, if you click on the a baot in version `1.0.4` your camera will not updated like this :
![image](https://user-images.githubusercontent.com/30438580/64517582-ec4d8c80-d2f0-11e9-9ae5-7ec0505478ca.png)

However, your character is fine 😂 
![image](https://user-images.githubusercontent.com/30438580/64517709-26b72980-d2f1-11e9-9a34-97b8b09bd975.png)

**Comment by Kaydax** [comment]
Working on a fix for it now for 1.0.6

**Comment by Kaydax** [comment]
Fixed as of 1.0.6 - 1.1.0
