### ISSUE TITLE
BetterPortals Remove Animation

### ISSUE THREAD

**Issue by Traincrafter111** [Kaydax/Ido#29]
Hi I found that if BP mod is installed and you go Third Person your caracter is invisible while swiming.
I know is a minor bug but I would like if you could fix it.
thanks

**Comment by TheMCSpacePro** [comment]
I'ma going to also let the author of Better Portals know about this. To see if we can get this fixed sooner.

**Comment by Kaydax** [comment]
He already is aware and he made a patch for it. But it isn't his fault really, it's on my end as Ido replaces the render player class out right. I will be working on an update soon that will make Ido more comparability friendly

**Comment by lag42** [comment]
actually betterportals released an [update](https://www.curseforge.com/minecraft/mc-mods/betterportals/files/2787100) not too long ago that shouldn't do this specifically

**Comment by Traincrafter111** [comment]
Thanks so much Ill be waiting the update!

**Comment by TheMCSpacePro** [comment]
The creator of Better Portals already fixed it on their end. BP 3.5 has the fix.

**Comment by Kaydax** [comment]
Since it was patched on their end I will close this issue, but I will be working on a major patch on my end to make this mod more compatible with other mods
