### ISSUE TITLE
Incompatibility with Real First Person Render 2

### ISSUE THREAD

**Issue by floral-qua-floral** [Kaydax/Ido#32]
The [Real First Person 2](https://www.curseforge.com/minecraft/mc-mods/real-first-person-render) mod by rejahtavi encounters an issue when used alongside Ido in which the playermodel will obscure the camera when swimming or crawling. The issue is probably best fixed on RFP2's side, however the mod's developer has said in [this issue thread](https://github.com/rejahtavi/rfp2/issues/11) that they can't implement a fix, as Ido doesn't give other mods an easy way to check what state the player is in. Implementing such a thing would allow RFP2's author to (hopefully) implement proper compatibility so these two mods can work together without issue, and could also potentially benefit other mods that might want to integrate with Ido in similar ways.

**Comment by Kaydax** [comment]
I already know that Ido has incompatibility with mods that use custom rendering. I will be working on a fix for it soon when I have the time

**Comment by Kaydax** [comment]
I have added the ability to check if the player is swimming / crawling or is sneaking in 1.1.0 so developers can use that if they want. If the developer of RFP2 needs anything else tell them to ask
