### ISSUE TITLE
Animation Issue with Galacticraft

### ISSUE THREAD

**Issue by Traincrafter111** [Kaydax/Ido#34]
Hi I found out that if you have galacticraft and you shift under a slab you will start crawling.
Heres a picture.
![2019-09-30_13 23 43](https://user-images.githubusercontent.com/44734869/65905453-31139300-e386-11e9-9af2-1193e7cc0755.png)

**Comment by Kaydax** [comment]
What armor are you wearing. Is it only caused when you have those on or just if the mod is installed?

**Comment by Traincrafter111** [comment]
Just if the mod installed. Im not wearing any armor from galacticraft.

**Comment by Kaydax** [comment]
I don't have the issue when I have galacticraft installed. So it must be another conflicting mod. If you find any evidence to suggest that it's an actual incompatibility I will be happy to hear it, but from the testing I have done I can not find anything that makes this happen.
