### ISSUE TITLE
1 issue and 1 detail I'd like to point out

### ISSUE THREAD

**Issue by XKane55** [Kaydax/Ido#36]
1st of all, every time I open up and close a door (and I'm still somewhat in the door which happens to me all the time), the player crouches which is pretty annoying (Good mod though). 

Also, when you get to the ground, in 1.13, the view from standing to crouching is smooth. There is like a transition between the two views. But, with this mod, our view is teleported from the standing view to the crouching view. Which is sometimes disorienting. I'd like it to be more like the original version.

Great mod by the way. I needed this so bad!

**Comment by Kaydax** [comment]
On the project page i say to install RandomPatches to enable this. Go get that and you should have the smooth camera. Also i know about the door issue and will be fixing it soon

**Comment by XKane55** [comment]
Okay, thanks! :)
