### ISSUE TITLE
Problems with Forge 2847

### ISSUE THREAD

**Issue by mactso** [Kaydax/Ido#40]
Hey, we are looking into an issue with forge 2847.

The player is going into swim/crawl mode on slabs and also getting stuck on the edge of blocks unable to move up with autojump.

And having trouble moving on some materials like grass and diorite.  It moves very slowly.

From the player perspective, you are inside the rock but take no smothering damage and can still move thru it.

Ido works fine in Forge 2815.

**Comment by Kaydax** [comment]
Do you have any other mods installed?

**Comment by mactso** [comment]
sec.. checking

**Comment by mactso** [comment]
Okay,  there still may be an issue on Diorite.  With Ido loaded,  my feet are in the block.
We'll do an "ido only" test now.

**Comment by mactso** [comment]
Okay, no issue with IDO alone.  Going to try and find which mod is interacting with IDO that makes us sink into Diorite but will close this issue.  I'll report a new issue if I determine which mod is causing us to sink .5 blocks into Diorite.
