### ISSUE TITLE
jumping against ceiling makes you auto sneak for a moment

### ISSUE THREAD

**Issue by WarlordWossman** [Kaydax/Ido#5]
just noticed jumping in a 2 high hallway and even a 3 wide hallway makes you auto sneak for a short moment when you hit the ceiling which looks very weird

**Comment by Kaydax** [comment]
This may be do to the way I'm checking for sneaking under the slabs. I will try to look into this and work out a fix

**Comment by Kaydax** [comment]
I have fixed the issue and it will be pushed into the next release once i fix some other issues up. One issue left is sneak jumping into a ceiling pushes you backwards, but this is a small issue that I may fix.
