### ISSUE TITLE
[Mod Compatibility] Armourer's Workshop models do not render on swimming entities

### ISSUE THREAD

**Issue by DoomRater** [Kaydax/Ido#50]
Using Armourer's Workshop 0.50.1.596, any time I enter a swimming animation, Armourer's Workshop custom renders disappear from the model.  I suspect that is because it is rendering its own copy of the model as opposed to rotating the existing one.

**Comment by Kaydax** [comment]
This may be related to the fact the mod does the stupid thing of replacing a core minecraft class. We are working on a rework for that right now, so it may be fixed in the coming week

**Comment by Kaydax** [comment]
Should be fixed in the latest commit, if you find any other issue with the mod please let me know

**Comment by DoomRater** [comment]
The use of Obfuscate is a known incompatibility with Armourer's Workshop. while the armor will render fine, reskinned items will not show up in third person renders.  This is almost heart breaking news.

**Comment by Kaydax** [comment]
Its the best I can do, and at that point that should be on the creator of Armourer's Workshop to fix tbh

**Comment by DoomRater** [comment]
Fair enough.  Risky has stated there is nothing he can do to make item rendering work on his end, and I simply don't know enough about rendering pipelines to check myself.
