### ISSUE TITLE
Conflict with Mo'Bends

### ISSUE THREAD

**Issue by BillZhucn** [Kaydax/Ido#53]
When using Ido with Mo'Bends, changing camera perspective (F5) will result in a crash of client. 
[crash-2020-10-17_17.57.03-client.txt](https://github.com/Kaydax/Ido/files/5395411/crash-2020-10-17_17.57.03-client.txt)

**Comment by Kaydax** [comment]
This is a known incompatibility because of the way we handle the animations for swimming and crawling. I am planning to rework the mod to fix this issue when I have the time

**Comment by Kaydax** [comment]
There is no longer a crash, but it still looks bad
