### ISSUE TITLE
Animation Error - Help Appreciated

### ISSUE THREAD

**Issue by NoteTheHate** [Kaydax/Ido#64]
Hello!
I have noticed that when using Ido, the animations are not applied. (Crawling/Swimming, in particular.) As such, whenever I use the animations, they just keep my character standing straight up (as seen in these images.) Is this a Incompatibility with Optifine, or something else?

Modlist is a large one, but here it is.

 Additional Lights
 AppleSkin
 BetterBedrockGenerator
Yung's Better Caves
Yung's Better MIneshafts
Cathedral Addon for Chisel
Chisel
Chisel & Bits
Clarity (Underwater Vision)
Clay Conversion
Collective
Comforts
Controlling
CreativeCore
CTM
DoubleSlabs
Dynamic Trees
Dynamic Trees Traverse Addon
Farseek
Flesh2Leather
Forgelin
MrCrayFish Furniture
FutureMC
Hwyla
Ido
IronBackpacks
Just Enough Items
JourneyMap
Just Rotten Flesh to Leather
LittleTiles
Nature's Compass
Not Enough IDs
Obfuscate
Optifine
Path under Gates
Pixelmon Extras
Pixelmon Reforged
RandomPatches
Save My Stronghold
Secret Rooms Mod
Sit
Spartan Shields
Spartan Weaponry
StepUp
Streams
Traverse
VanillaFix
VeinMiner
VillageSpawnPoint
WorldEdit

Broken Animations:
![image](https://user-images.githubusercontent.com/88590917/128607068-f0e9a05e-cbc6-42e1-9c04-d7a9814a2403.png)
![image](https://user-images.githubusercontent.com/88590917/128607081-fe007d78-bd64-45de-8778-fc1d58705adb.png)

Apologies for the Modlist length, but I needed Assistance.
Cheers!

**Comment by Kaydax** [comment]
I can't seem to find any mod that should be conflicting with ido. I recommend either trying the release version and not the beta and if nothing else works id say to test to see what mods could be doing it by removing and adding them back one by one.

**Comment by NoteTheHate** [comment]
Alright. I shall try that. Thank you!

**Comment by NoteTheHate** [comment]
Can confirm that the beta was the reason for the animation error. Thank you for suggestion to change Ido versions!
