### ISSUE TITLE
Will the animation of climbing ladders be updated in the future?

### ISSUE THREAD

**Issue by GalaxyZEROX** [Kaydax/Ido#65]
Will the animation of climbing ladders be updated in the future? (When you meet a ladder, Fujiman and the like will climb)

**Comment by Kaydax** [comment]
What do you mean by this? Ido is just a backport of existing features (Swimming / Crawling) in 1.13+ into 1.12, not an animation mod or advanced movement mod of any sort.

**Comment by Kaydax** [comment]
Im assuming the issue has nothing to do with ido and im just going to close it out
