### ISSUE TITLE
Configurable crawling keybind?

### ISSUE THREAD

**Issue by 20o** [Kaydax/Ido#66]
Could you add a crawling keybind that's configured to be off by default, just for those who'd like to use it?

**Comment by Kaydax** [comment]
The mod is meant to be a direct backport of the newer features into 1.12.2, without adding anything else to it. I understand people want a button but it will never be added to the mod directly. If someone would like to make a companion mod that works with ido to add said feature, that would be fine, but Ido itself will never have such feature.
