### ISSUE TITLE
Broken Clothing Layer & Mild Incompatibility. 

### ISSUE THREAD

**Issue by Ecdragonz** [Kaydax/Ido#8]
Hey There! I'm glad this mod is getting updated more and more to improve it! 

It seems the clothing layer and the hat layer are both messed up when swimming or crawling. I only have two mods loaded, that being randompatches. (As is recommended for smooth camera movement) and Ido itself. 

Here are some screenshots:

Swimming
![2019-07-25_15 38 58](https://user-images.githubusercontent.com/45206350/61903521-b136fb80-aef2-11e9-8d36-925444f89964.png)

![2019-07-25_15 38 56](https://user-images.githubusercontent.com/45206350/61903533-b4ca8280-aef2-11e9-8ce0-ec1873f7fdf0.png)

Crawling:
![2019-07-25_15 40 32](https://user-images.githubusercontent.com/45206350/61903840-84371880-aef3-11e9-9b0f-6dd7dc76b0a2.png)

![2019-07-25_15 40 36](https://user-images.githubusercontent.com/45206350/61903563-c1e77180-aef2-11e9-8dac-3942d86db5c1.png)

As for the incompatibility. More player models (Which i installed after taking the previous screenshots) causes some issues where the player model wont be translated properly into the crawling or swimming model. I made the arms bigger on my character to show the scaling gets reset and added the eyes to my character. No idea if this is anything you can fix on your end, but I figured id mention it so it comes to your attention if anything can be done. 

![2019-07-25_15 43 57](https://user-images.githubusercontent.com/45206350/61903757-505bf300-aef3-11e9-8677-9790e9d6e0df.png)

![2019-07-25_15 44 13](https://user-images.githubusercontent.com/45206350/61903771-55b93d80-aef3-11e9-8fd4-74ce3441187f.png)

Thanks for your time! Hope you keep updating this!

**Comment by Kaydax** [comment]
More player models will not be supported as it conflicts with our mod as it also changes the way the player model is scaled and rendered. Our mod works in the same way by rotating and scaling the default player model to allow for the crawling and swimming pose to work correctly. I will fix the skin layers though as that is a issue that can be fixed

**Comment by Kaydax** [comment]
Rendering issue fixed in 1.0.3

**Comment by Ecdragonz** [comment]
thank you!
